export const PAGINATION_COUNT = 4;
export const LEADERBOARD_LIMIT = 200 / PAGINATION_COUNT;
export const DEFAULT_LIST_ELEMENT_SIZE = 161;
export const BREAKPOINTS = {
  mobile: 640,
};
export const LEADERBOARD_PLAYER_BATTLES = 30;
export const PROFILE_PLAYER_BATTLES = 100;
export const MAX_DISPLAYED_PLAYER_BATTLES = 20;
